import Head from 'next/head'
import { GoogleMaps } from '@/components/Maps/GoogleMaps'
import Overlay from '@/components/Overlay'
import React, { useState } from 'react'

export default function Home() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false)
  const toggleDrawer = () => {
    setIsDrawerOpen((prevState) => !prevState)
  }

  return (
    <>
      <Head>
        <title>irvinesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative h-screen w-full">
          <GoogleMaps setIsDrawerOpen={setIsDrawerOpen} isDrawerOpen={isDrawerOpen}/>
          <Overlay/>
        </div>
      </main>
    </>
  )
}
